name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r yolov5_hse/requirements.txt
  
    - name: Run Tests
      run: |
        pytest
  build:
    runs-on: ubuntu-latest
    
    steps:
     - name: Installing poetry
       run: |
         pip install poetry
         poetry build
