name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: set up checkout
      uses: actions/checkout@v1
    - name: Set up Python Environment
      uses: actions/setup-python@v1
    - name: Update pip
      run: |
        python -m pip install --upgrade pip
    - name: Install requirements
      run: |
        pip install -r yolov5_hse/requirements.txt
  
    - name: Run Tests
      run: |
        pytest
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Python Environment
      uses: actions/setup-python@v2
    - name: Installing poetry
      run: |
        echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
        pip install poetry
    - name: Building the package
      run: |
        poetry build
